# Generated by Django 5.2 on 2025-06-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_title', models.CharField(max_length=100)),
                ('tip_content', models.TextField()),
                ('tip_image', models.ImageField(blank=True, null=True, upload_to='tips/images/')),
                ('tip_video', models.FileField(blank=True, null=True, upload_to='tips/videos/')),
            ],
        ),
    ]
