# Generated by Django 5.2 on 2025-06-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_orators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orators',
            name='content',
            field=models.TextField(),
        ),
    ]
