# Generated by Django 5.2 on 2025-06-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_alter_orators_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='orators',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
